spring.application.name=service_clientes

server.port=8085

# Conexión a DB Clientes
spring.datasource.url=jdbc:mysql://localhost:3306/db_clientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
