spring.application.name=service-combos
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/db_combos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui/index.html
server.forward-headers-strategy=framework

# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/api/combos/v3/api-docs

# Obligar a probar mediante el Gateway
springdoc.server-url=http://localhost:9090