spring.application.name=service-abastecimiento
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/db_abastecimiento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true