spring.application.name=service-resenas
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/db_resenas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update