spring.application.name=service-postventa
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/db_postventa?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update